version: '3.0'
services:
  web_title2:
    container_name: web_title2
    build: ./
    ports: 
      - "3000:3000"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true
